name: Build and Release Task Manager

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [win32]

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.jsのセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # pkgをインストール
      - name: Install pkg
        run: npm install -g pkg

      # exeファイルをビルド
      - name: Build exe
        run: pkg . --targets node14-win-x64 --output task-manager.exe

      # ビルドされたexeファイルをGitHubリリースにアップロード
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v1.0.0' # バージョンに合わせて更新
          release_name: 'Task Manager Release'
          draft: false
          prerelease: false

      # exeファイルをリリースにアップロード
      - name: Upload exe to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./task-manager.exe
          asset_name: task-manager.exe
          asset_content_type: application/octet-stream
